name: Pre-release

on:
  push:
    branches:
      - "main" 

jobs:
  create-release:
    name: Build and Create Commit Release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Bump package version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm version "0.0.0-${{ env.SHORT_SHA }}" --git-tag-version false

      - name: Run build
        run: pnpm build

      - name: Update repository
        run: |
          git add .
          git commit -am "Build for commit ${{ env.SHORT_SHA }}"
          git push

      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_banking/src/client
          cp ./{LICENSE,README.md,fxmanifest.lua} ./temp/ox_banking
          cp ./src/client/client.lua ./temp/ox_banking/src/client
          cp -r ./{dist,data,locales} ./temp/ox_banking
          cd ./temp && zip -r ../ox_banking.zip ./ox_banking

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Commit: ${{ env.SHORT_SHA }}'
          prerelease: false
          files: ox_banking.zip
